name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    uses: KevinDeBenedetti/github-workflows/.github/workflows/release.yml@main
    with:
      config-file: release/release-please-config-release.json
      manifest-file: release/.release-please-manifest.json
    secrets: inherit
